In [2]:
import numpy as np
num1=np.array([[2,3,4],[4,2,1],[1,4,2]])
num2=np.array([[5,3,2],[4,3,5],[5,1,3]])
print("array 1:")
print(num1)
print("array 2:")
print(num2)
print("\n multiply two given arrays:")
print(np.multiply(num1,num2))

array 1:
[[2 3 4]
 [4 2 1]
 [1 4 2]]
array 2:
[[5 3 2]
 [4 3 5]
 [5 1 3]]

 multiply two given arrays:
[[10  9  8]
 [16  6  5]
 [ 5  4  6]]


In [3]:
import numpy as np
nums=np.array([[3,2,np.nan],[2,4,1],[np.nan,2,np.nan]])
print("Original Array:")
print(nums)
print("\n find the missing data of the array:")
print(np.isnan(nums))

Original Array:
[[ 3.  2. nan]
 [ 2.  4.  1.]
 [nan  2. nan]]

 find the missing data of the array:
[[False False  True]
 [False False False]
 [ True False  True]]


In [5]:
import numpy as np
array1 = np.array([0,10,20,30,40])
print("array1:",array1)
array2 = [0,30]
print("array2:",array2)
print("Compare each element of array1 and array2")
print(np.in1d(array1,array2))

array1: [ 0 10 20 30 40]
array2: [0, 30]
Compare each element of array1 and array2
[ True False False  True False]


In [14]:
import numpy as np

List = [1, 2, 3, 4, 5]
Array = np.array(List)
print('Array:\n', Array)
file = open("file1.txt", "w+")
content = str(Array)
file.write(content)
file.close()
file = open("file1.txt", "r")
content = file.read()
print("\nContent in file1.txt:\n", content)
file.close()

Array:
 [1 2 3 4 5]

Content in file1.txt:
 [1 2 3 4 5]


In [17]:
import numpy as np
x = np.linspace(2.5, 6.5,30)

print(x)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


In [8]:
import pandas as pd
data = {'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]}
series = pd.Series(data)
result = series.apply(pd.Series).stack().reset_index(drop=True)
print(result)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64


In [9]:
import pandas as pd
data = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5}
series = pd.Series(data)
value = 3
condition = lambda x: x > value
subset = series[series.apply(condition)]
print(subset)

D    4
E    5
dtype: int64


In [11]:
import pandas as pd
s = pd.Series(['apple', 'banana', 'cherry', 'date', 'banana', 'cherry', 'date', 'apple', 'banana'])
most_frequent_value = s.value_counts().index[0]
s = s.apply(lambda x: x if x == most_frequent_value else 'Other')
print(s)

0     Other
1    banana
2     Other
3     Other
4    banana
5     Other
6     Other
7     Other
8    banana
dtype: object


In [13]:
import pandas as pd
s = pd.Series([10, 22, 35, 40, 53, 60, 71, 80, 95, 109])
positions = s[s % 5 == 0].index
print(positions)

Int64Index([0, 2, 3, 5, 7, 8], dtype='int64')


In [18]:
import pandas as pd
series1 = pd.Series(['Php', 'Python', 'Java', 'C#'])
print("Original Series:")
print(series1)
result = series1.map(lambda x: len(x))
print("\nNumber of characters in each word in the said series:")
print(result)

Original Series:
0       Php
1    Python
2      Java
3        C#
dtype: object

Number of characters in each word in the said series:
0    3
1    6
2    4
3    2
dtype: int64


In [19]:
import pandas as pd
from dateutil.parser import parse
date_series = pd.Series(['Jan 2015', 'Feb 2016', 'Mar 2017', 'Apr 2018', 'May 2019'])
print("Original Series:")
print(date_series)
print("\nNew dates:")
result = date_series.map(lambda d: parse('11 ' + d))
print(result)

Original Series:
0    Jan 2015
1    Feb 2016
2    Mar 2017
3    Apr 2018
4    May 2019
dtype: object

New dates:
0   2015-01-11
1   2016-02-11
2   2017-03-11
3   2018-04-11
4   2019-05-11
dtype: datetime64[ns]


In [22]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anand', 'Divya', 'karthik', 'Jhanu', 'Eswar', 'Manoj', 'Prasanna'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5],
        'attempts': [1, 3, 2, 3, 2, 3, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g' ]

df = pd.DataFrame(exam_data , index=labels)
print(df)

       name  score  attempts qualify
a     Anand   12.5         1     yes
b     Divya    9.0         3      no
c   karthik   16.5         2     yes
d     Jhanu    NaN         3      no
e     Eswar    9.0         2      no
f     Manoj   20.0         3     yes
g  Prasanna   14.5         1     yes


In [24]:
import numpy as np

exam_data  = {'name': ['Anand', 'Divya', 'karthik', 'Jhanu', 'Eswar', 'Manoj', 'Prasanna'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5,],
        'attempts' : [1, 3, 2, 3, 2, 3, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g']

df = pd.DataFrame(exam_data , index=labels)
print("Number of attempts in the examination is greater than 2:")
print(df[df['attempts'] > 2])

Number of attempts in the examination is greater than 2:
    name  score  attempts qualify
b  Divya    9.0         3      no
d  Jhanu    NaN         3      no
f  Manoj   20.0         3     yes


In [25]:
import pandas as pd
import numpy as np
exam_data  = {'name': ['Anand', 'Divya', 'karthik', 'Jhanu', 'Eswar', 'Manoj', 'Prasanna'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5,],
        'attempts' : [1, 3, 2, 3, 2, 3, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g']

df = pd.DataFrame(exam_data , index=labels)
print("Original rows:")
print(df)
print("\nAppend a new row:")
df.loc['k'] = [1, 'Suresh', 'yes', 15.5]
print("Print all records after insert a new record:")
print(df)
print("\nDelete the new row and display the original  rows:")
df = df.drop('k')
print(df)

Original rows:
       name  score  attempts qualify
a     Anand   12.5         1     yes
b     Divya    9.0         3      no
c   karthik   16.5         2     yes
d     Jhanu    NaN         3      no
e     Eswar    9.0         2      no
f     Manoj   20.0         3     yes
g  Prasanna   14.5         1     yes

Append a new row:
Print all records after insert a new record:
       name   score attempts qualify
a     Anand    12.5        1     yes
b     Divya     9.0        3      no
c   karthik    16.5        2     yes
d     Jhanu     NaN        3      no
e     Eswar     9.0        2      no
f     Manoj    20.0        3     yes
g  Prasanna    14.5        1     yes
k         1  Suresh      yes    15.5

Delete the new row and display the original  rows:
       name score attempts qualify
a     Anand  12.5        1     yes
b     Divya   9.0        3      no
c   karthik  16.5        2     yes
d     Jhanu   NaN        3      no
e     Eswar   9.0        2      no
f     Manoj  20.0        3    

In [26]:
import pandas as pd
import numpy as np
exam_data  = {'name': ['Anand', 'Divya', 'karthik', 'Jhanu', 'Eswar', 'Manoj', 'Prasanna'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5,],
        'attempts' : [1, 3, 2, 3, 2, 3, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
df = pd.DataFrame(exam_data , index=labels)
print("Orginal rows:")
print(df)
df = df.sort_values(by=['name', 'score'], ascending=[False, True])
print("Sort the data frame first by ‘name’ in descending order, then by ‘score’ in ascending order:")
print(df)

Orginal rows:
       name  score  attempts qualify
a     Anand   12.5         1     yes
b     Divya    9.0         3      no
c   karthik   16.5         2     yes
d     Jhanu    NaN         3      no
e     Eswar    9.0         2      no
f     Manoj   20.0         3     yes
g  Prasanna   14.5         1     yes
Sort the data frame first by ‘name’ in descending order, then by ‘score’ in ascending order:
       name  score  attempts qualify
c   karthik   16.5         2     yes
g  Prasanna   14.5         1     yes
f     Manoj   20.0         3     yes
d     Jhanu    NaN         3      no
e     Eswar    9.0         2      no
b     Divya    9.0         3      no
a     Anand   12.5         1     yes


In [27]:
import pandas as pd
import numpy as np
exam_data  = {'name': ['Anand', 'Divya', 'karthik', 'Jhanu', 'Eswar', 'Manoj', 'Prasanna'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5,],
        'attempts' : [1, 3, 2, 3, 2, 3, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
df = pd.DataFrame(exam_data , index=labels)
print("Original rows:")
print(df)
print("\nReplace the 'qualify' column contains the values 'yes' and 'no'  with True and  False:")
df['qualify'] = df['qualify'].map({'yes': True, 'no': False})
print(df)

Original rows:
       name  score  attempts qualify
a     Anand   12.5         1     yes
b     Divya    9.0         3      no
c   karthik   16.5         2     yes
d     Jhanu    NaN         3      no
e     Eswar    9.0         2      no
f     Manoj   20.0         3     yes
g  Prasanna   14.5         1     yes

Replace the 'qualify' column contains the values 'yes' and 'no'  with True and  False:
       name  score  attempts  qualify
a     Anand   12.5         1     True
b     Divya    9.0         3    False
c   karthik   16.5         2     True
d     Jhanu    NaN         3    False
e     Eswar    9.0         2    False
f     Manoj   20.0         3     True
g  Prasanna   14.5         1     True


In [31]:
import pandas as pd 
import numpy as np 

exam_data  = {'name': ['Anand', 'Divya', 'karthik', 'Jhanu', 'Eswar', 'Manoj', 'Prasanna'],
        'score': [12.5, np.inf, 16.5, -np.inf, 9, 20, 14.5,],
        'attempts' : [1, 3, 2, 3, 2, 3, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
df = pd.DataFrame(exam_data) 
df


name  score  attempts qualify
0     Anand   12.5         1     yes
1     Divya    inf         3      no
2   karthik   16.5         2     yes
3     Jhanu   -inf         3      no
4     Eswar    9.0         2      no
5     Manoj   20.0         3     yes
6  Prasanna   14.5         1     yes