In [13]:
#Create a vector (array) of 1XN dimension representing N-
#dimensional feature vector of a sample. Write a program to
#compute the mean and variance of the elements present in the array.

import numpy as np
vector = np.array([51, 52, 53, 54, 55])
mean = np.mean(vector)
variance = np.var(vector, ddof=1)
print("Mean: ", mean)
print("Variance: ", variance)

Mean:  53.0
Variance:  2.5


In [3]:
#Create two vectors each of dimension 1XM each representing N-
#dimensional feature vector of a sample. Write a program to
#compute the Covariance between them.

import numpy as np
array_a = np.array([5, 6, 7, 8, 9])
array_b = np.array([10, 11, 12, 13, 14])
covariance = np.cov(array_a, array_b, ddof=1)[0][1]
print("Covariance: ", covariance)


Covariance:  2.5


In [4]:
#Create two vectors each of dimension 1XN. Write a program to compute the Correlation between them.

import numpy as np
array_one = np.array([3, 6, 9, 12, 15])
array_two = np.array([5, 10, 15, 20, 25])
correlation_result = np.corrcoef(array_one, array_two)[0][1]
print("Correlation: ", correlation_result)


Correlation:  1.0


In [12]:
#Create a Matrix of MXN dimension representing the M-dimensional
#feature vector for N number of samples i. e (i,j)th entry of the matrix
#represents the ith feature of jth sample. Write a program to compute
#the covariance matrix and correlation matrix. Comment on takeaways from these matrixes.

import numpy as np
matrix = np.array([[4,5,6], [7,8,9], [20,21,22]])
covariance_matrix = np.cov(matrix, rowvar=False)
correlation_matrix = np.corrcoef(matrix, rowvar=False)
print("Covariance matrix:")
print(covariance_matrix)
print("Correlation matrix:")
print(correlation_matrix)

Covariance matrix:
[[72.33333333 72.33333333 72.33333333]
 [72.33333333 72.33333333 72.33333333]
 [72.33333333 72.33333333 72.33333333]]
Correlation matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
